[package]
name = "souls_conflict"
version = "2.1.2"
edition = "2024"
license = "MIT"
description = "Fast, deep conflict detector and merger for Dark Souls Remastered mods"
repository = "https://github.com/nobodyttk/SoulsConflict-Mod-Manager-and-Merger-for-Dark-Souls-Remastered"

[dependencies]
flate2 = "1.1.10"
image = "0.24"
rars = "0.9.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tao = "0.16"
wry = "0.24"
zip = "2.2"

[build-dependencies]
winres = "0.1.12"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "unwind"
strip = "debuginfo"
